[package]
name = "threadstat-shared"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {workspace=true}
perf-ffi = { path = "../perf-ffi", features = ["pfm"] }
string-intern = {workspace = true}
non-empty = { path = "../non-empty" }
threadstat-message = {path = "../threadstat-message/"}
poll = {path = "../poll/"}

[lints]
workspace = true
